// Regenerates each demo app's puzzle fixture: snapshots the current daily
// puzzle, translates it to the domain `Puzzle` shape, verifies it is solvable,
// and writes a copy into every app that feeds the element.
//
// Usage: pnpm fixture

import { readdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const API = 'https://cognipuzzle-embed.com/embed/telex/daily/current'

// ESM-only package exporting only "." — read its exports map rather than
// hard-coding a dist path. Resolved from npm-demo so the fixture is built by the
// version that app pins.
const PKG_DIR = join(ROOT, 'apps/npm-demo/node_modules/@cogniplay/puzzle')
const pkg = JSON.parse(readFileSync(join(PKG_DIR, 'package.json'), 'utf8'))
const entry = pkg.exports?.['.']?.import
if (!entry) throw new Error('@cogniplay/puzzle has no ESM export for "."')
const { wirePuzzleToDomain } = await import(
  pathToFileURL(join(PKG_DIR, entry)).href
)
console.log(`using @cogniplay/puzzle@${pkg.version}`)

const res = await fetch(API)
if (!res.ok) throw new Error(`${API} -> HTTP ${res.status}`)
const body = await res.json()
const puzzle = wirePuzzleToDomain(body.puzzle)
console.log(`source: ${API}`)
console.log(`served date: ${body.date} (${body.outlet}/${body.challenge})`)

// ---- Prove solvability before writing: exact cover over board minus blockers.
const key = ([x, y]) => `${x},${y}`
const boardSet = new Set(puzzle.board.map(key))
const blocked = new Set((puzzle.blockers ?? []).map(key))
const open = [...boardSet].filter((c) => !blocked.has(c))
const pieceCells = puzzle.pieces.reduce(
  (s, p) => s + p.orientations[0].length,
  0,
)
const maxX = Math.max(...puzzle.board.map((c) => c[0]))
const maxY = Math.max(...puzzle.board.map((c) => c[1]))

const placements = puzzle.pieces.map((p) => {
  const out = []
  for (const o of p.orientations)
    for (let dx = -maxX; dx <= maxX; dx++)
      for (let dy = -maxY; dy <= maxY; dy++) {
        const cells = o.map(([x, y]) => key([x + dx, y + dy]))
        if (cells.every((c) => boardSet.has(c) && !blocked.has(c)))
          out.push(cells)
      }
  return out
})

const used = new Set()
const taken = puzzle.pieces.map(() => false)
function search(depth) {
  if (depth === puzzle.pieces.length) return true
  const target = open.find((c) => !used.has(c))
  if (!target) return false
  for (let i = 0; i < placements.length; i++) {
    if (taken[i]) continue
    for (const pl of placements[i]) {
      if (!pl.includes(target) || pl.some((c) => used.has(c))) continue
      pl.forEach((c) => used.add(c))
      taken[i] = true
      if (search(depth + 1)) return true
      taken[i] = false
      pl.forEach((c) => used.delete(c))
    }
  }
  return false
}

console.log(`open cells: ${open.length} | piece cells: ${pieceCells}`)
if (open.length !== pieceCells) {
  console.error(
    'REFUSING to write: piece cells do not cover the open board exactly.',
  )
  process.exit(1)
}
if (!search(0)) {
  console.error('REFUSING to write: this puzzle has no solution.')
  process.exit(1)
}
console.log('solvable: yes')

// ---- Write into every app that has a public/ directory.
const header = `// Generated by tools/generate-fixture.mjs — run \`pnpm fixture\` to refresh.
// Snapshot of the ${body.outlet} daily puzzle (${body.date}), in domain \`Puzzle\` shape.`

const body_ = `${header}
window.cogniplaySample = {
  puzzle: ${JSON.stringify(puzzle, null, 2).split('\n').join('\n  ')},
}
`

// iframe-demo is excluded: it has no Cogniplay dependency of any kind.
const FIXTURE_APPS = ['bundle-demo', 'npm-demo']

const appsDir = join(ROOT, 'apps')
const targets = FIXTURE_APPS.filter((a) =>
  existsSync(join(appsDir, a, 'public')),
)
if (!targets.length) {
  console.error(`none of ${FIXTURE_APPS.join(', ')} have a public/ directory`)
  process.exit(1)
}
for (const app of targets) {
  writeFileSync(join(appsDir, app, 'public/sample-data.js'), body_)
  console.log(`wrote apps/${app}/public/sample-data.js`)
}
for (const app of FIXTURE_APPS.filter((a) => !targets.includes(a))) {
  console.log(`skipped apps/${app} (not scaffolded yet)`)
}
console.log('\nRun `pnpm format` — prettier owns the generated file.')
